# pretext: Generate your Data
title: Modern Information Retrieval
description: Sharif University of Technology Computer Science Modern Information Retrieval course
university: Sharif University of Technology
course: 40324- Fall 2025
author: Dr. Hamid Beigy

course_videos: 50+
course_duration: 50
course_lessons: 20
course_resources: 30+
